### ISSUE TITLE
how to link scripts

### ISSUE THREAD

**Issue by mykola-den** [rajyraman/crm-client-scripts#1]
Hi! After you build ts file for dynamics CRM form, how do you link onLoad() function to actual form. I'm new to TS and don't see what will be our output.
By the way, what tools do you use to deploy client scripts?
 thank you

**Comment by rajyraman** [comment]
Typescript compiles to JavasScript, and it is the compiled JavaScript you will be deploying to Dynamics CRM. You can customise the build output location and various other things in tsconfig.json (Refer https://www.typescriptlang.org/docs/handbook/tsconfig-json.html). You can use XrmToolBox's _WebResources Manager_ tool to deploy the compiled JavaScript to CRM. Once the script is in CRM, you can use XrmToolBox's _Form Libraries Manager_ to associate it to an entity form. I usually do the actual function to event association through the standard CRM UI (_Form -> Form Properties -> Event Handlers_).

**Comment by mykola-den** [comment]
I see now. From the code I had a feeling that those classes somehow magically bind to CRM form events. Yet we still have our good old onLoad() :smile:  

Did you use **tfs** and **visual studio** in your development workflow? 

As for me it would look like:
- install [crm developer extensions](https://visualstudiogallery.msdn.microsoft.com/0f9ab063-acec-4c55-bd6c-5eb7c6cffec4)
- write code in TS 
- compile and then deploy output to crm-organization using web-resource deployer.
- commit all to tfs in ts and js folders

Does it look legit?

**Comment by rajyraman** [comment]
I generally upload an empty  JavaScript webresource, set up the event handlers in forms and then use Fiddler Auto Responder rules to serve the js from my local folder. Once everything seems right, I then deploy it to CRM and checkin to TFS
